// =============================================================================
// DATABASE: LOCATIONS (settings[]) + HOLIDAY SETTINGS
// Indonesian Amateur Shot Generator
// Each entry: { env, arch, props, era_id }
// =============================================================================

const settings = [

    // ===========================================================================
    // TIMELESS BASIC — Works in any era, no strong era markers
    // ===========================================================================
    { env: "PLAIN NEUTRAL COLOR WALL (WHITE OR CREAM)", arch: "MINIMALIST BLANK WALL WITH NO DISTRACTIONS", props: "NONE, PURE FOCUS ON SUBJECT", era_id: "TIMELESS_BASIC" },
    { env: "BLURRED INDOOR BACKGROUND (BOKEH ROOM)", arch: "INDISTINGUISHABLE INDOOR ROOM, SHALLOW DEPTH", props: "SOFT BOKEH LIGHTS IN BACKGROUND", era_id: "TIMELESS_BASIC" },
    { env: "SIMPLE ROOM CORNER", arch: "PLAIN CORNER WITH SOFT NATURAL LIGHTING", props: "MINIMAL DISTRACTIONS, POTTED PLANT MAYBE", era_id: "TIMELESS_BASIC" },
    { env: "OUTDOOR BLURRED GREENERY (TAMAN / GARDEN)", arch: "NATURE", props: "TREES AND LEAVES OUT OF FOCUS", era_id: "TIMELESS_BASIC" },
    { env: "AESTHETIC MINIMALIST CAFE (CONCRETE WALLS)", arch: "PLAIN CEMENT WALLS AND MINIMAL DECOR", props: "SIMPLE WOODEN CHAIR, COFFEE CUP", era_id: "TIMELESS_BASIC" },
    { env: "TRADITIONAL WARTEG (WARUNG TEGAL)", arch: "SMALL LOCAL EATERY WITH GLASS FOOD DISPLAY", props: "GLASS DISPLAY OF INDONESIAN FOOD, PEOPLE EATING IN BACKGROUND", era_id: "TIMELESS_BASIC" },
    { env: "SIMPLE PHOTO STUDIO (STUDIO FOTO KTP)", arch: "PLAIN BLUE OR RED SEAMLESS BACKDROP", props: "STUDIO LIGHTING STAND, STOOL CHAIR", era_id: "TIMELESS_BASIC" },
    { env: "MODERN ELEVATOR INTERIOR", arch: "STAINLESS STEEL WALLS, BRIGHT LED LIGHTS, LARGE MIRROR", props: "ELEVATOR BUTTONS PANEL, HANDRAIL", era_id: "TIMELESS_BASIC" },
    { env: "MUSIC INSTRUMENT STORE", arch: "WOODEN WALLS COVERED IN GUITARS AND MUSIC GEAR", props: "VARIOUS ACOUSTIC AND ELECTRIC GUITARS HANGING", era_id: "TIMELESS_BASIC" },
    { env: "EMPTY SCHOOL HALLWAY (KORIDOR SEKOLAH)", arch: "PAINTED CONCRETE WALLS, LOCKERS OR BULLETIN BOARD", props: "FLUORESCENT LIGHTS, LINOLEUM FLOOR", era_id: "TIMELESS_BASIC" },
    { env: "LOCAL HOSPITAL OR KLINIK WAITING AREA", arch: "PLASTIC CHAIRS, STERILE WALLS, TV ON WALL", props: "QUEUE NUMBER SCREEN, POTTED PLANT", era_id: "TIMELESS_BASIC" },
    { env: "BARBERSHOP / PANGKAS RAMBUT", arch: "BARBER CHAIR, LARGE MIRROR, SHELF OF PRODUCTS", props: "SCISSORS, CLIPPERS, AFTERSHAVE BOTTLES", era_id: "TIMELESS_BASIC" },
    { env: "PARISIAN STYLE STREET CAFE (OUTDOOR BISTRO)", arch: "SIDEWALK CAFE SEATING WITH RATTAN CHAIRS", props: "ROUND BISTRO TABLE, CHAMPAGNE GLASSES, EUROPEAN STREET VIEW", era_id: "TIMELESS_BASIC" },
    { env: "EUROPEAN CITY STREET (LONDON VIBE)", arch: "URBAN STREET WITH HISTORIC BRICK BUILDINGS", props: "RED TELEPHONE BOOTH, DOUBLE DECKER BUS IN BACKGROUND", era_id: "TIMELESS_BASIC" },
    { env: "JAPANESE STYLE WOODEN CAFE INTERIOR", arch: "EXPOSED WOODEN BEAMS, WARM PENDANT LIGHTS", props: "WOODEN TABLES, COFFEE CUPS, AESTHETIC VIBE", era_id: "TIMELESS_BASIC" },
    { env: "EMPTY BASKETBALL COURT", arch: "OUTDOOR OR INDOOR COURT WITH FADED PAINTED LINES", props: "BASKETBALL HOOP, BACKBOARD, CHAIN LINK FENCE", era_id: "TIMELESS_BASIC" },
    { env: "ROOFTOP WITH CITY SKYLINE VIEW", arch: "CONCRETE ROOFTOP WITH LOW PARAPET WALLS", props: "CITY BUILDINGS AND SKY IN BACKGROUND", era_id: "TIMELESS_BASIC" },
    { env: "SMALL WARUNG KOPI (KEDAI KOPI LOCAL)", arch: "WOODEN STALL OR SMALL SHOPHOUSE", props: "GLASS CUPS OF KOPI TUBRUK, PLASTIC CHAIRS, CIGARETTE SMOKE", era_id: "TIMELESS_BASIC" },

    // ===========================================================================
    // MODERN 2020S — Gen-Z, contemporary Indonesian urban & outdoor life
    // ===========================================================================

    // --- Kos, Apartment, Bedroom ---
    { env: "MESSY INDONESIAN KOS-KOSAN ROOM", arch: "SMALL NARROW ROOM WITH PEELING PAINT AND CHEAP WOOD FURNITURE", props: "RUMPLED BED, FLOOR FAN, GALON DISPENSER, HANGING CLOTHES ON DOOR HOOK", era_id: "MODERN_2020S" },
    { env: "AESTHETIC MINIMALIST KOS ROOM (KOREAN VIBE)", arch: "WHITE WALLS, LIGHT WOOD FURNITURE, FAIRY LIGHTS", props: "NEAT WHITE BED SHEET, FULL-LENGTH MIRROR, MACBOOK ON DESK, STUDY LAMP", era_id: "MODERN_2020S" },
    { env: "CLUTTERED UNIVERSITY STUDENT KOS (KOST MAHASISWA)", arch: "NARROW WALLS COVERED IN STICKY NOTES AND POSTERS", props: "PILE OF TEXTBOOKS, CHEAP PLASTIC LAUNDRY BASKET, MESSY DESK WITH SNACKS", era_id: "MODERN_2020S" },
    { env: "DARK GAMER BEDROOM (KAMAR GAMER)", arch: "SOUNDPROOF FOAM WALL PANELS AND RGB NEON STRIP LIGHTING", props: "GAMING CHAIR, DUAL MONITORS, MECHANICAL KEYBOARD, EMPTY ENERGY DRINK CANS", era_id: "MODERN_2020S" },
    { env: "LUXURY JAKARTA APARTMENT BEDROOM", arch: "MODERN INTERIOR WITH FLOOR-TO-CEILING WINDOWS SHOWING CITY SKYLINE AT NIGHT", props: "KING SIZE BED, WARM LAMPS, EXPENSIVE PERFUME BOTTLES ON DRESSER", era_id: "MODERN_2020S" },
    { env: "COZY LIVING ROOM COUCH (SOFA RUMAH)", arch: "MINIMALIST WALLS, BEIGE OR GREY SOFA", props: "COUCH PILLOWS, BACKPACK ON SOFA, TV IN BACKGROUND", era_id: "MODERN_2020S" },
    { env: "SUNLIT ROOM WITH DRAMATIC SHADOW PLAY", arch: "INDOOR ROOM NEAR A LARGE WINDOW", props: "DRAMATIC SUNLIGHT AND GRID-SHADOW ON WALLS FROM WINDOW BLINDS", era_id: "MODERN_2020S" },
    { env: "LUXURY MARBLE BATHROOM (KAMAR MANDI MEWAH HOTEL)", arch: "FLOOR-TO-CEILING MARBLE TILES, LARGE ORNATE BACKLIT MIRROR", props: "PREMIUM TOILETRIES, DESIGNER HANDBAG ON COUNTER, WARM VANITY LIGHTS", era_id: "MODERN_2020S" },
    { env: "DARK ROOM LIT ONLY BY PHONE SCREEN", arch: "PITCH BLACK ROOM, TOTAL DARKNESS", props: "GLOWING SMARTPHONE SCREEN REFLECTING BLUE LIGHT ON FACE", era_id: "MODERN_2020S" },
    { env: "SITTING INSIDE A BATHTUB (FULLY CLOTHED)", arch: "GRUNGE TILED BATHROOM WALLS", props: "EMPTY BATHTUB, TILES, MOODY VIBE", era_id: "MODERN_2020S" },

    // --- Cafe & Food ---
    { env: "CROWDED STARBUCKS INSIDE A JAKARTA MALL", arch: "WOODEN PANELING, GREEN MERMAID LOGO, BARISTAS IN GREEN APRONS IN BACKGROUND", props: "ICED COFFEE CUP WITH NAME WRITTEN, OPEN LAPTOP, BUSY ATMOSPHERE", era_id: "MODERN_2020S" },
    { env: "J.CO DONUTS CAFE IN A MALL", arch: "BRIGHT ORANGE AND WOODEN INTERIOR", props: "TRAY OF GLAZED DONUTS, ICED J.COFFEE CUP, BRIGHT LIGHTS", era_id: "MODERN_2020S" },
    { env: "AESTHETIC RESTAURANT BOOTH (DIMLY LIT)", arch: "WARM VINTAGE LIGHTING, STRIPED UPHOLSTERY SOFA, BRICK WALL", props: "AESTHETIC PLATED FOOD ON WOODEN TABLE", era_id: "MODERN_2020S" },
    { env: "TERAS MINIMARKET (INDOMARET / ALFAMART)", arch: "CONVENIENCE STORE GLASS FRONT WITH BLUE AND RED STRIPES, NEON SIGNS", props: "PLASTIC CHAIRS AND TABLE, MOTORCYCLES PARKED, ICED COFFEE IN HAND", era_id: "MODERN_2020S" },
    { env: "AISLE OF MINIMARKET (INDOMARET / ALFAMART)", arch: "NARROW AISLES WITH BRIGHT FLUORESCENT WHITE LIGHTING", props: "SHELVES PACKED WITH COLORFUL LOCAL SNACKS AND BEVERAGE FRIDGES", era_id: "MODERN_2020S" },
    { env: "WARMINDO (WARUNG MAKAN INDOMIE)", arch: "BRIGHTLY LIT SMALL EATERY WITH RED AND YELLOW BANNERS", props: "BOWLS OF INSTANT NOODLES, WOODEN BENCHES, ICED SWEET TEA IN PLASTIC CUP", era_id: "MODERN_2020S" },
    { env: "MIE GACOAN RESTAURANT", arch: "CROWDED OPEN-AIR MODERN NOODLE JOINT WITH RED AND BLACK BRANDING", props: "SPICY NOODLES ON PLATES, DIM SUM, PLASTIC CHAIRS, BUSTLING YOUTH CROWD", era_id: "MODERN_2020S" },
    { env: "OUTDOOR CAFE SEATING AREA (GARDEN CAFE)", arch: "WOODEN BENCH, CAFE WINDOW DISPLAY, HANGING PLANTS", props: "DRINK MENU POSTER, RETRO LAMP, BOX COVERED IN STICKERS", era_id: "MODERN_2020S" },
    { env: "MODERN BAKERY FACADE (EUROPEAN STYLE)", arch: "WOOD-FRAMED WINDOWS, LIGHT BLUE AND WHITE TILES", props: "BLACK CHALKBOARD SIGN, METAL RAILING, TILED STAIRS", era_id: "MODERN_2020S" },
    { env: "LATE NIGHT CONVENIENCE STORE AISLE (MALAM)", arch: "FLUORESCENT LIT AISLES, QUIET LATE NIGHT ATMOSPHERE", props: "COLORFUL SNACK SHELVES, REFRIGERATORS, MAYBE ONE BORED CASHIER", era_id: "MODERN_2020S" },
    { env: "STREET FOOD BAKSO OR MIE AYAM STALL (GEROBAK)", arch: "TENTED STREET STALL WITH PLASTIC SIGNAGE", props: "BOWLS, PLASTIC CHAIRS, WOODEN TABLES, STEAMING BROTH", era_id: "MODERN_2020S" },
    { env: "CITY NIGHT STREET FOOD ROW (LESEHAN / KAKI LIMA)", arch: "STREET SIDEWALK LINED WITH FOOD CARTS AND BRIGHT BANNERS", props: "PLASTIC RED CHAIRS, VARIETY OF LOCAL FOOD, PEOPLE EATING", era_id: "MODERN_2020S" },
    { env: "SITTING ON A RED PLASTIC CHAIR AT NIGHT (WARUNG PINGGIR JALAN)", arch: "INDONESIAN STREET SIDEWALK AT NIGHT", props: "RED PLASTIC CHAIR, STREET FOOD TENT IN BACKGROUND, NEON LIGHTS", era_id: "MODERN_2020S" },

    // --- Mall & Retail ---
    { env: "LUXURY MALL RESTROOM (TOILET MALL JAKARTA)", arch: "MARBLE SINKS, WARM AESTHETIC LIGHTING, LARGE CLEAN MIRRORS", props: "AUTOMATIC SOAP DISPENSERS, FRESH FLOWERS ON COUNTER, SHOPPING BAGS", era_id: "MODERN_2020S" },
    { env: "HIGH-END MALL CORRIDOR (CENTRAL PARK / GRAND INDONESIA VIBE)", arch: "POLISHED MARBLE FLOORS, LUXURY BRAND STOREFRONTS, HIGH CEILINGS", props: "DESIGNER SHOPPING BAGS, ESCALATOR IN BACKGROUND", era_id: "MODERN_2020S" },
    { env: "THRIFT SHOP / TOKO BAJU BEKAS LOKAL", arch: "CROWDED CLOTHING RACKS, WARM INDOOR LIGHTING", props: "VINTAGE CLOTHES HANGING, MIRRORS, PRICE TAGS", era_id: "MODERN_2020S" },
    { env: "KOREAN STYLE SELFIE PHOTOBOOTH (PHOTOBOX)", arch: "TIGHT CRAMPED BOOTH, PASTEL BLUE OR PINK BACKDROP", props: "CAMERA LENS, PHOTO STRIP EXAMPLE ON WALL, PROPS BOX", era_id: "MODERN_2020S" },
    { env: "COIN LAUNDROMAT (LAUNDRY KOIN)", arch: "ROWS OF METAL WASHING MACHINES, WHITE TILES", props: "LAUNDRY BASKETS, NEON SIGNS, FLUORESCENT LIGHT", era_id: "MODERN_2020S" },

    // --- Automotive & Transport ---
    { env: "INSIDE A LUXURY CAR (ALPHARD / MERCEDES / BMW)", arch: "PREMIUM CREAM OR BLACK LEATHER SEATS, MODERN CAR INTERIOR WITH AMBIENT LIGHTING", props: "STEERING WHEEL OR BACK SEAT, DASHBOARD GLOW, SUNROOF", era_id: "MODERN_2020S" },
    { env: "BACK SEAT OF TOYOTA INNOVA REBORN", arch: "CAR INTERIOR, SLIGHTLY NARROW", props: "VISIBLE TOYOTA LOGO, SEAT TEXTURE, INFOTAINMENT SCREEN GLOW", era_id: "MODERN_2020S" },
    { env: "NIGHT TAXI BACK SEAT (GOJEK OR GRAB CAR)", arch: "DARK CAR INTERIOR", props: "CITY NEON LIGHTS SHINING THROUGH WINDOW GLASS, DRIVER SILHOUETTE", era_id: "MODERN_2020S" },
    { env: "PARKING LOT JDM CAR MEET", arch: "CONCRETE PARKING LOT AT NIGHT, UNDER TUNGSTEN LAMPS", props: "MODIFIED JDM SPORTS CAR (RX7 OR EVO) IN BACKGROUND, PEOPLE GATHERED", era_id: "MODERN_2020S" },
    { env: "SITTING ON THE HOOD OF A CAR (DI ATAS KAP MOBIL)", arch: "OUTDOOR STREET OR PARKING LOT", props: "CAR HOOD, HEADLIGHTS ON, NIGHT OR DUSK BACKGROUND", era_id: "MODERN_2020S" },
    { env: "LEANING ON A VINTAGE CAR ON A COBBLESTONE STREET", arch: "COBBLESTONE STREET, NEW YORK OR EUROPEAN STYLE BUILDINGS WITH FIRE ESCAPES", props: "VINTAGE MERCEDES BENZ OR VW BEETLE", era_id: "MODERN_2020S" },
    { env: "RIDING A VINTAGE VESPA SCOOTER ON A BUSY STREET", arch: "ASPHALT ROAD WITH SHOPFRONTS AND TRAFFIC", props: "GREEN OR WHITE VINTAGE VESPA SCOOTER", era_id: "MODERN_2020S" },
    { env: "WINDING MOUNTAIN ROAD NEXT TO VESPA", arch: "SCENIC ASPHALT MOUNTAIN ROAD, LUSH GREEN BACKDROP", props: "CLASSIC LIGHT BLUE VESPA SCOOTER PARKED NEARBY, FOG OR MIST", era_id: "MODERN_2020S" },
    { env: "INSIDE A COMMUTER TRAIN HOLDING HANDRAIL (KRL)", arch: "MODERN TRAIN INTERIOR WITH YELLOW AND RED GRAB HANDLES", props: "PASSENGERS WITH MASKS AND SMARTPHONES, BLURRED WINDOWS", era_id: "MODERN_2020S" },
    { env: "JAKARTA MRT STATION", arch: "CLEAN MODERN SUBWAY ARCHITECTURE WITH GREY AND GREEN ACCENTS", props: "BLURRED COMMUTERS, LED DEPARTURE SIGNS, GLASS DOORS", era_id: "MODERN_2020S" },
    { env: "TRAIN OR TRAM WINDOW SEAT", arch: "VEHICLE INTERIOR WITH LARGE GLASS WINDOW", props: "FOGGY WINDOW WITH CONDENSATION FINGER-DRAWN HEART, BLURRED LANDSCAPE", era_id: "MODERN_2020S" },
    { env: "BACK OF AN OPEN PICKUP TRUCK (MOBIL BAK TERBUKA)", arch: "METAL TRUCK BED, WIND EXPOSURE", props: "WIND BLOWING HAIR, STREET OR COUNTRYSIDE IN BACKGROUND BLURRED", era_id: "MODERN_2020S" },
    { env: "INSIDE A TRADITIONAL ANGKOT (PUBLIC MINIVAN)", arch: "BLUE OR RED PUBLIC MINIVAN INTERIOR, VERY CRAMPED", props: "PASSENGERS SITTING FACING EACH OTHER, OPEN SLIDING DOOR, STICKERS ON CEILING", era_id: "MODERN_2020S" },
    { env: "CITY BUS STOP (HALTE TRANSJAKARTA)", arch: "GLASS BUS SHELTER ON A BUSY STREET", props: "CITY TRAFFIC, BUS STOP SIGN, ROUTE MAP ON WALL", era_id: "MODERN_2020S" },
    { env: "LUXURY AIRLINE BUSINESS CLASS CABIN", arch: "SPACIOUS PRIVATE SEAT PODS, WOOD AND LEATHER FINISHES, WARM AMBIENT LIGHTING", props: "CHAMPAGNE GLASS, LARGE ENTERTAINMENT SCREEN, PLUSH PILLOW, WINDOW VIEW", era_id: "MODERN_2020S" },
    { env: "GARUDA INDONESIA ECONOMY CABIN", arch: "NARROW AIRPLANE AISLE, SEATS WITH DISTINCTIVE TOSCA GREEN AND ORANGE PATTERNS", props: "SEATBACK SCREEN SHOWING FLIGHT MAP, INFLIGHT MEAL TRAY, CABIN CREW IN BACKGROUND", era_id: "MODERN_2020S" },
    { env: "LUXURY PRIVATE JET CABIN", arch: "CREAM LEATHER CAPTAIN CHAIRS, WOODEN VENEER TABLES, WARM LED STRIP LIGHTING", props: "CHAMPAGNE ON ICE, EXPENSIVE LEATHER BAG, ROUND AIRPLANE WINDOWS", era_id: "MODERN_2020S" },

    // --- Urban / Street ---
    { env: "PEDESTRIAN CROSSWALK (ZEBRA CROSS) FROM ABOVE", arch: "ASPHALT ROAD WITH ALTERNATING WHITE AND GREY STRIPES", props: "SPECKLED STONE TILES, PAPER COFFEE CUP ON THE GROUND", era_id: "MODERN_2020S" },
    { env: "CITY PEDESTRIAN BRIDGE (JEMBATAN PENYEBERANGAN ORANG)", arch: "STEEL AND CONCRETE BRIDGE OVER A BUSY ROAD", props: "METAL RAILINGS, CITY TRAFFIC BELOW, YELLOW LINE", era_id: "MODERN_2020S" },
    { env: "CONCRETE CITY STAIRS (TANGGA BETON)", arch: "MODERN CONCRETE ARCHITECTURE, METAL RAILINGS", props: "URBAN METROPOLIS BUILDINGS IN BACKGROUND", era_id: "MODERN_2020S" },
    { env: "URBAN ALLEYWAY WITH YELLOW STUCCO WALLS", arch: "NARROW STREET WITH VIBRANT YELLOW STUCCO WALLS AND TILES", props: "STREET SIGNS, PAVED SIDEWALK, MOTORBIKE PASSING", era_id: "MODERN_2020S" },
    { env: "NIGHT PEDESTRIAN WALKWAY (MALIOBORO / BRAGA VIBE)", arch: "STREET SIDEWALK WITH VINTAGE LAMP POSTS AND WARM ORANGE GLOW", props: "STREET LAMPS, PEDESTRIANS, DARK NIGHT SKY", era_id: "MODERN_2020S" },
    { env: "CITY NIGHT LIGHTS BOKEH (JALAN MALAM KOTA)", arch: "URBAN STREET AT NIGHT", props: "BLURRED NEON AND CAR LIGHTS, BOKEH CIRCLES IN BACKGROUND", era_id: "MODERN_2020S" },
    { env: "OUTDOOR PARK OR GARDEN (TAMAN KOTA)", arch: "LUSH GREENERY, TREES, MANICURED GRASS", props: "PARK BENCH, LAMP POST, NATURAL LIGHT", era_id: "MODERN_2020S" },
    { env: "CONCRETE SKATEPARK (SKATEPARK KOTA)", arch: "CONCRETE RAMPS, LEDGES, HALF-PIPE", props: "SKATEBOARDS, GRAFFITI ON WALLS, STICKERS", era_id: "MODERN_2020S" },
    { env: "CCTV SECURITY CAMERA VIEW (SUDUT TINGGI)", arch: "CORNER OF A ROOM OR ALLEYWAY, HIGH CORNER MOUNT", props: "GRAINY FOOTAGE LOOK, TIMESTAMP ON SCREEN, FISH-EYE DISTORTION", era_id: "MODERN_2020S" },
    { env: "CONVEX STREET MIRROR (CERMIN TIKUNGAN)", arch: "STREET CORNER, YELLOW POLE", props: "ROUND CONVEX MIRROR, TRAFFIC SIGNS, DISTORTED REFLECTION", era_id: "MODERN_2020S" },
    { env: "OUTDOOR MOTORCYCLE PARKING EVENT (MOTOCYCLE SHOW)", arch: "ASPHALT PARKING LOT WITH BANNERS AND FLAGS", props: "CUSTOM CAFE RACER OR SCRAMBLER MOTORCYCLE, PEOPLE IN BACKGROUND", era_id: "MODERN_2020S" },
    { env: "DIRTY ROADSIDE PARKING AREA", arch: "PAVED STREET SIDE WITH RUBBLE AND BROKEN TILES", props: "CHEAP CARS PARKED, DIRT, AMBIENT NOISE", era_id: "MODERN_2020S" },

    // --- Nature & Outdoor ---
    { env: "BEACH AT SUNSET (PANTAI SENJA)", arch: "OPEN SANDY BEACH, BEAUTIFUL GRADIENT SUNSET SKY", props: "GENTLE WAVES CRASHING, WET SAND, HORIZON LINE", era_id: "MODERN_2020S" },
    { env: "NIGHT BEACH WITH CITY LIGHTS IN DISTANCE", arch: "DARK SAND BEACH, NIGHT SKY WITH STARS", props: "GLOWING CITY SKYLINE OR ILLUMINATED BRIDGE IN THE BACKGROUND, WAVES", era_id: "MODERN_2020S" },
    { env: "WOODEN PIER OVER CALM TURQUOISE OCEAN", arch: "WOODEN BOARDWALK EXTENDING OVER WATER", props: "CALM BLUE OCEAN WATER, SMALL YELLOW BUOYS FLOATING", era_id: "MODERN_2020S" },
    { env: "LAKESIDE PARK PICNIC (DANAU TAMAN KOTA)", arch: "GRASSY LAKESHORE WITH TREES", props: "PICNIC BLANKET, ICED DRINK IN JAR, TREES AND LAKE IN BACKGROUND", era_id: "MODERN_2020S" },
    { env: "SANDY BEACH PATH LEADING TO OCEAN", arch: "NATURAL SAND DIRT PATH THROUGH COASTAL GREENERY", props: "OCEAN WAVES VISIBLE AT END OF PATH, COASTAL SHRUBS", era_id: "MODERN_2020S" },
    { env: "WOODEN SWING IN PINE FOREST (HUTAN PINUS MAGELANG)", arch: "TALL PINE TREES, NATURE PARK, MISTY MOUNTAIN AIR", props: "WOODEN SWING SEAT HUNG FROM PINE TREE, MOUNTAIN VIEW IN BACKGROUND", era_id: "MODERN_2020S" },
    { env: "CITY LAKE WOODEN DECK (DANAU KOTA)", arch: "WOODEN BOARDWALK NEXT TO URBAN LAKE, SKYSCRAPERS IN DISTANCE", props: "BLACK CHAIN BARRIER, GREENERY, COOL BREEZE", era_id: "MODERN_2020S" },
    { env: "SCENIC MOUNTAIN OVERLOOK (PUNCAK VIEW POINT)", arch: "CONCRETE BARRIER ON THE EDGE OF A CLIFF OR HILL", props: "WINDING ROAD FAR BELOW, LUSH GREEN MOUNTAINS, CLOUD LAYER", era_id: "MODERN_2020S" },
    { env: "PADDLEBOARDING ON CLEAR TURQUOISE SEA", arch: "OPEN WATER, KARST LIMESTONE CLIFFS IN BACKGROUND", props: "PADDLEBOARD, CLEAR WATER REFLECTIONS, BRIGHT SKY", era_id: "MODERN_2020S" },
    { env: "TRADITIONAL WOODEN BOAT ON BROWN RIVER (SUNGAI KALIMANTAN)", arch: "WOODEN BOAT DECK, JUNGLE RIVER ATMOSPHERE", props: "MUDDY BROWN RIVER WATER, TROPICAL JUNGLE ON RIVERBANK, OUTBOARD MOTOR", era_id: "MODERN_2020S" },
    { env: "OUTDOOR CAFE TERRACE SEATING", arch: "WICKER PATIO FURNITURE, WARM SUNLIGHT, GARDEN VIEW", props: "COFFEE CUP ON TABLE, SMALL POTTED SUCCULENT, RATTAN CHAIR", era_id: "MODERN_2020S" },
    { env: "LAKESIDE PROMENADE (JALAN TEPI DANAU)", arch: "PAVED PATHWAY NEXT TO A LARGE LAKE", props: "MOUNTAINS IN THE DISTANCE, CLEAR BLUE WATER, LAMP POSTS", era_id: "MODERN_2020S" },
    { env: "TENNIS COURT ON A SUNNY DAY", arch: "GREEN HARD TENNIS COURT, CHAINLINK FENCE", props: "PALM TREES IN BACKGROUND, BENCH ON SIDE", era_id: "MODERN_2020S" },
    { env: "FISHING VILLAGE PIER (DERMAGA NELAYAN)", arch: "WOODEN CONCRETE PIER WITH YELLOW PAINTED BARRIERS", props: "FISHING BOATS MOORED, BLUE SEA WATER, FISHING NETS", era_id: "MODERN_2020S" },
    { env: "OUTDOOR PARK FOUNTAIN AREA", arch: "PAVED PLAZA WITH WATER FOUNTAIN CENTER", props: "WATER SPRAY, PIGEONS, PEOPLE IN BACKGROUND", era_id: "MODERN_2020S" },
    { env: "RICE FIELD TERRACE (SAWAH TERASERING — BALI OR JAVA)", arch: "STEPPED TERRACED RICE PADDIES, LUSH GREEN", props: "COCONUT TREES, FARMERS IN BACKGROUND, MISTY MOUNTAINS", era_id: "MODERN_2020S" },

    // --- Luxury & Leisure ---
    { env: "5-STAR LUXURY HOTEL POOLSIDE", arch: "LUXURY INFINITY POOL WITH CLEAR BLUE WATER, MODERN RESORT ARCHITECTURE", props: "SUN LOUNGERS, CABANAS, WHITE TOWELS, TROPICAL PALM TREES, SUNGLASSES", era_id: "MODERN_2020S" },
    { env: "LUXURY BALI BEACH CLUB POOLSIDE (POTATO HEAD / OMNIA STYLE)", arch: "MASSIVE INFINITY POOL FACING THE OCEAN, BAMBOO AND MODERN ARCHITECTURE", props: "DAYBEDS, COLORFUL COCKTAILS, DJ BOOTH IN BACKGROUND, CROWD IN SWIMWEAR", era_id: "MODERN_2020S" },
    { env: "CROWDED INDONESIAN WATERPARK (WAHANA AIR)", arch: "MASSIVE COLORFUL WATER SLIDES, LAZY RIVER, BRIGHT BLUE POOLS", props: "YELLOW TUBE FLOATS, SPLASHING WATER, FAMILIES PLAYING IN BACKGROUND", era_id: "MODERN_2020S" },
    { env: "LUXURY YACHT DECK AT SUNSET", arch: "WOODEN YACHT DECK WITH WHITE SAILS, CITY SKYLINE IN BACKGROUND", props: "CALM SEA WATER, CHAMPAGNE GLASSES, SUNSET LIGHT", era_id: "MODERN_2020S" },
    { env: "BALCONY OVERLOOKING LAKE COMO OR AMALFI COAST VIBE", arch: "CLASSIC STONE BALUSTRADE, RED BOUGAINVILLEA FLOWERS", props: "DEEP BLUE SEA, MOUNTAINS IN DISTANCE, MOTOR BOATS", era_id: "MODERN_2020S" },
    { env: "LABUAN BAJO PHINISI BOAT DECK (NTT)", arch: "TRADITIONAL INDONESIAN WOODEN SAILING BOAT DECK WITH TALL MASTS", props: "SUNGLASSES, BEANBAGS, KOMODO ISLAND IN DISTANCE, SUNSET", era_id: "MODERN_2020S" },

    // --- Events & Entertainment ---
    { env: "INDOOR WEDDING RECEPTION (KONDANGAN GEDUNG)", arch: "DECORATED BALLROOM WITH STAGE AND FLORAL ARRANGEMENTS", props: "ROUND TABLES WITH FOOD, GUESTS IN BATIK AND KEBAYA", era_id: "MODERN_2020S" },
    { env: "FOOTBALL STADIUM TRIBUNE AMONG THE CROWD", arch: "STADIUM SEATING, BRIGHT STADIUM FLOODLIGHTS", props: "CROWD OF SUPPORTERS, CLUB SCARVES AND FLAGS, BLURRED FANS", era_id: "MODERN_2020S" },
    { env: "OUTDOOR MUSIC FESTIVAL CROWD (LIKE JOYLAND OR WE THE FEST)", arch: "OPEN OUTDOOR FIELD CONCERT, LARGE CROWD", props: "LARGE CONCERT STAGE, HUGE CROWD OF PEOPLE IN BACKGROUND, DUST IN AIR", era_id: "MODERN_2020S" },
    { env: "LIVE CONCERT STAGE (PERFORMING)", arch: "MASSIVE STAGE PLATFORM, STAGE RIGGING, BRIGHT CONCERT SPOT LIGHTS", props: "MICROPHONE STAND, STAGE MONITORS, HUGE CROWD IN THE BACKGROUND", era_id: "MODERN_2020S" },
    { env: "CONCERT PHOTOGRAPHY PIT (FROM PIT)", arch: "EDGE OF A HIGH CONCERT STAGE VIEWED FROM BELOW", props: "STAGE LIGHTS POINTING DOWN, METALLIC BARRICADE, CONCERT CROWD VIBE", era_id: "MODERN_2020S" },
    { env: "CONCERT BACKSTAGE (BELAKANG PANGGUNG)", arch: "DARK INDUSTRIAL ARENA HALLWAY OR BLACK TENT", props: "BLACK FLIGHT CASES (HARDCASE), COILED CABLES, RACKS OF EQUIPMENT", era_id: "MODERN_2020S" },
    { env: "NIGHTCLUB IN SCBD JAKARTA (CLUB MALAM MEWAH)", arch: "LUXURY INDOOR CLUB WITH HUGE FLOOR-TO-CEILING LED SCREENS AND CHANDELIERS", props: "VIP LEATHER SOFAS, EXPENSIVE BOTTLES WITH SPARKLERS, LASER LIGHTS", era_id: "MODERN_2020S" },
    { env: "INDOOR SUPERCLUB IN BALI (LIKE SAVAYA OR CANGGU CLUB)", arch: "MASSIVE DANCEFLOOR WITH MOVING KINETIC LIGHTING FIXTURES ON THE CEILING", props: "DANCING CROWD, CONFETTI RAIN, LED WALLS", era_id: "MODERN_2020S" },
    { env: "UNDERGROUND TECHNO CLUB IN SURABAYA OR JAKARTA", arch: "DARK INDUSTRIAL ROOM WITH CONCRETE PILLARS AND INTENSE STROBE LIGHTS", props: "DJ BOOTH, SWEATY DANCING CROWD, SMOKE MACHINE", era_id: "MODERN_2020S" },
    { env: "OUTDOOR ROOFTOP GIG (INDIE CONCERT KECIL)", arch: "ROOFTOP TERRACE WITH MINIMAL STAGE SETUP, CITY LIGHTS IN BACKGROUND", props: "MUSICIANS PLAYING, SMALL CROWD, STRING LIGHTS", era_id: "MODERN_2020S" },
    { env: "CITY SQUARE WITH FERRIS WHEEL (ALUN-ALUN ATAU FESTIVAL)", arch: "BRICK PAVED PEDESTRIAN SQUARE", props: "TALL FERRIS WHEEL, ICE CREAM TRUCK, PEDESTRIANS IN BACKGROUND", era_id: "MODERN_2020S" },
    { env: "INDOOR SPORTS BADMINTON HALL (GOR BULUTANGKIS)", arch: "INDOOR SPORTS HALL WITH HIGH CEILING, BRIGHT LED COURT LIGHTING", props: "BADMINTON NET, COURT LINES, SHUTTLECOCK", era_id: "MODERN_2020S" },

    // --- Iconic Indonesian Spots ---
    { env: "M BLOC SPACE JAKARTA", arch: "TROPICAL VINTAGE 1950S COLONIAL HOUSES CONVERTED INTO TRENDY CAFES, EXPOSED BRICK, OUTDOOR WALKWAY", props: "VIBRANT STREET ART MURALS, NEON LIGHTS, COFFEE CUPS", era_id: "MODERN_2020S" },
    { env: "GELORA BUNG KARNO (GBK) STADIUM COMPLEX", arch: "MASSIVE CIRCULAR STADIUM WITH DISTINCTIVE WHITE STEEL ROOF RING AND RED RUNNING TRACK", props: "WATER BOTTLES, PEOPLE JOGGING IN BACKGROUND, ARTIFICIAL TURF", era_id: "MODERN_2020S" },
    { env: "CANGGU BALI BEACH CABANA", arch: "TROPICAL BAMBOO ARCHITECTURE, THATCHED ROOF OVERLOOKING THE OCEAN", props: "BEER BOTTLES, SUNGLASSES, COLORFUL BEANBAGS, SURFERS IN BACKGROUND", era_id: "MODERN_2020S" },
    { env: "BRAGA STREET BANDUNG (REVITALIZED)", arch: "EUROPEAN ART DECO COLONIAL BUILDINGS ALONG NARROW COBBLESTONE STREET", props: "VINTAGE STREET LAMPS, PEDESTRIANS, ARTISAN VENDORS", era_id: "MODERN_2020S" },
    { env: "KESAWAN SQUARE MEDAN (SUMATRA)", arch: "REVITALIZED 19TH CENTURY DUTCH COLONIAL BUILDINGS TURNED INTO CAFES", props: "COFFEE CUPS, HANGING STREET LIGHTS, TRISHAWS", era_id: "MODERN_2020S" },
    { env: "MASJID 99 KUBAH MAKASSAR (EVENING)", arch: "FUTURISTIC MOSQUE ARCHITECTURE, DOZENS OF BRIGHT ORANGE AND YELLOW DOMES, WATERFRONT PROMENADE", props: "PEOPLE WALKING AROUND, REFLECTION ON SEA WATER AT SUNSET", era_id: "MODERN_2020S" },
    { env: "JEMBATAN YOUTEFA JAYAPURA (PAPUA)", arch: "MASSIVE CURVED RED STEEL ARCH BRIDGE OVER THE BLUE BAY", props: "CARS PASSING BY, LUSH GREEN HILLS IN DISTANCE", era_id: "MODERN_2020S" },
    { env: "MANDALIKA CIRCUIT LOMBOK", arch: "MODERN ASPHALT RACING TRACK WITH RED TRIBAL PATTERNS ON RUNOFF AREAS", props: "UMBRELLAS AND RACING FANS TRIBUNE, PALM TREES", era_id: "MODERN_2020S" },
    { env: "CITY LAKE WOODEN DECK ANCOL JAKARTA", arch: "WOODEN BOARDWALK NEXT TO WATER, FERRIS WHEEL IN DISTANCE", props: "BLACK CHAIN BARRIER, GREENERY, CITY VIEW", era_id: "MODERN_2020S" },
    { env: "CO-WORKING SPACE (OPEN OFFICE AESTHETIC)", arch: "EXPOSED BRICK WALLS, POLISHED CONCRETE FLOORS, OPEN PLAN DESKS", props: "MACBOOKS, COFFEE CUPS, PLANTS, BLURRED COWORKERS", era_id: "MODERN_2020S" },
    { env: "BEACHSIDE WARUNG (PANTAI BALI STYLE)", arch: "BAMBOO AND THATCH WARUNG OVERLOOKING THE SEA", props: "PLASTIC CHAIR ON SAND, COLD BINTANG BEER, WAVES", era_id: "MODERN_2020S" },

    // ===========================================================================
    // HIPSTER 2010S — Indie, art, alternative, cafe culture
    // ===========================================================================
    { env: "TUMBLR AESTHETIC BEDROOM (2010s)", arch: "FAIRY LIGHTS DRAPED ACROSS THE CEILING, POLAROID PHOTO WALL", props: "UKULELE, RECORD PLAYER, MESSY BLANKETS, FILM PHOTOS", era_id: "HIPSTER_2010S" },
    { env: "MODERN WARKOP HANGOUT (TONGKRONGAN 2010s)", arch: "OPEN AIR STREET CORNER CAFE WITH BRIGHT LIGHTS, WOODEN TABLES", props: "BOWLS OF INDOMIE, COFFEE CUPS, ASHTRAYS, CIGARETTES", era_id: "HIPSTER_2010S" },
    { env: "PASAR SANTA JAKARTA VINTAGE MARKET", arch: "CRAMPED INDOOR MARKET KIOSKS WITH WOODEN SHELVES", props: "VINYL RECORDS, COFFEE DRIPPERS, VINTAGE CLOTHES", era_id: "HIPSTER_2010S" },
    { env: "CAR FREE DAY (CFD) BUNDARAN HI JAKARTA", arch: "WIDE EMPTY BOULEVARD WITH SKYSCRAPERS", props: "BICYCLES, FOOD STREET VENDORS, PEOPLE EXERCISING", era_id: "HIPSTER_2010S" },
    { env: "TEBING KERATON PINE FOREST BANDUNG", arch: "NATURAL PINE FOREST EDGE ON A CLIFF", props: "MIST, CAMPING GEAR, BINOCULARS", era_id: "HIPSTER_2010S" },
    { env: "ROOFTOP GIG IN SOUTH JAKARTA", arch: "EXPOSED BRICK OUTDOOR PATIO, CITY VIEW", props: "RED SOLO CUPS, GUITARS, FAIRY LIGHTS, SMALL CROWD", era_id: "HIPSTER_2010S" },
    { env: "STREET ART ALLEY IN YOGYAKARTA", arch: "BRICK WALLS COVERED IN COLORFUL MURALS", props: "VINTAGE VESPA PARKED NEARBY, ART STALLS", era_id: "HIPSTER_2010S" },
    { env: "MOUNT BROMO SUNRISE VIEWPOINT (EAST JAVA)", arch: "VOLCANIC LANDSCAPE WITH FOG AND DRAMATIC CALDERA", props: "RENTED HARDTOP JEEPS, WARM JACKETS, OTHER TOURISTS", era_id: "HIPSTER_2010S" },
    { env: "RAJA AMPAT PIAYNEMO VIEWPOINT (PAPUA)", arch: "WOODEN BOARDWALK OVERLOOKING STUNNING KARST ISLANDS", props: "CLEAR TURQUOISE WATER, TOURIST GROUPS", era_id: "HIPSTER_2010S" },
    { env: "JAM GADANG BUKITTINGGI (WEST SUMATRA)", arch: "TRADITIONAL CLOCK TOWER PLAZA", props: "HORSE CARRIAGES (BENDI), TOURISTS, LOCAL VENDORS", era_id: "HIPSTER_2010S" },
    { env: "JAKARTA EDM NIGHTCLUB (2010s ERA)", arch: "DARK ROOM WITH NEON LASER LIGHTS AND VIP BALCONY", props: "GLOWSTICKS, CROWD JUMPING, DJ BOOTH", era_id: "HIPSTER_2010S" },
    { env: "AESTHETIC INDIE CAFE RESTROOM", arch: "SUBWAY TILES, ROUND MIRRORS, DIM YELLOW LIGHTING", props: "AESOP HAND SOAP, POTTED PLANTS, SCENTED CANDLES", era_id: "HIPSTER_2010S" },
    { env: "CONCRETE SKATEPARK (HIPSTER ERA)", arch: "CONCRETE RAMPS AND LEDGES", props: "SKATEBOARDS, GRAFFITI WALLS, KIDS WATCHING", era_id: "HIPSTER_2010S" },
    { env: "THRIFT SHOP / TOKO VINTAGE", arch: "CLOTHING RACKS AND WARM INDOOR LIGHTING", props: "MIRRORS, VINTAGE CLOTHES HANGING, POLAROID PHOTOS ON WALL", era_id: "HIPSTER_2010S" },
    { env: "UNIVERSITY CAMPUS QUAD (KAMPUS SORE HARI)", arch: "OPEN GRASS AREA BETWEEN FACULTY BUILDINGS", props: "STUDENTS SITTING ON GRASS, BIKES, CAMPUS NOTICE BOARD", era_id: "HIPSTER_2010S" },
    { env: "INDIE RECORD STORE (TOKO KASET / VINYL)", arch: "WALLS LINED WITH VINYL AND CASSETTE SHELVES", props: "VINTAGE TURNTABLE, BAND MERCHANDISE, INDIE POSTERS", era_id: "HIPSTER_2010S" },
    { env: "CRAFT BEER BREWERY TAP ROOM (JAKARTA/BALI)", arch: "EXPOSED INDUSTRIAL PIPES, LARGE BREWING TANKS, WOODEN BAR", props: "PINT GLASSES, CHALK MENU BOARD, STOOLS", era_id: "HIPSTER_2010S" },
    { env: "BOOK CAFE (TOKO BUKU SEKALIGUS KAFE)", arch: "FLOOR TO CEILING BOOKSHELVES, COMFORTABLE READING CHAIRS", props: "STACKS OF BOOKS, READING GLASSES, COFFEE CUP", era_id: "HIPSTER_2010S" },
    { env: "ART GALLERY OPENING (GALERI SENI)", arch: "WHITE BOX GALLERY WALLS WITH ARTWORK HANGING", props: "WINE GLASSES, VISITORS LOOKING AT ART, GALLERY LIGHTING", era_id: "HIPSTER_2010S" },
    { env: "LOCAL FOOD BAZAAR / BAZAAR MAKANAN", arch: "OPEN WAREHOUSE OR PARK WITH FOOD BOOTHS", props: "STRING LIGHTS, ARTISAN FOOD VENDORS, PEOPLE QUEUING", era_id: "HIPSTER_2010S" },

    // ===========================================================================
    // Y2K 2000S — Early digital age Indonesia
    // ===========================================================================
    { env: "2000s TEENAGER BEDROOM", arch: "BRIGHT COLORED WALLS COVERED IN INDO POP BAND POSTERS (PETERPAN, SHEILA ON 7)", props: "CD BOOMBOX, BEANBAG CHAIR, NOKIA OR ERICSSON FLIP PHONES ON BED, CDs", era_id: "Y2K_2000S" },
    { env: "EXCELSO CAFE INSIDE A 2000S MALL", arch: "CLASSIC DARK WOOD INTERIOR AND DIM MOOD LIGHTING", props: "COFFEE SIPHON, LEATHER SOFAS, WOOD PANELING", era_id: "Y2K_2000S" },
    { env: "RENTAL PLAYSTATION 2 (PS2) ROOM (RENTAL PS)", arch: "DARK ROOM WITH CARPET AND LOW PLASTIC STOOLS", props: "MULTIPLE CRT TELEVISIONS AND TANGLED CONTROLLER CORDS, JOYSTICK", era_id: "Y2K_2000S" },
    { env: "CLUTTERED INDONESIAN WARNET (CYBERCAFE)", arch: "DIM LIGHTING, WOODEN CUBICLES PACKED TIGHTLY", props: "HEAVY CRT MONITORS, GAMING HEADSETS, PRINTED GAME GUIDES", era_id: "Y2K_2000S" },
    { env: "OLD 7-ELEVEN (SEVEL) HANGOUT SPOT", arch: "TILE FLOORS, GLASS WINDOWS, BRIGHT FLUORESCENT LIGHTING", props: "SLURPEE DRINKS, CHEESE NACHOS, PLASTIC TABLES, MAGAZINES", era_id: "Y2K_2000S" },
    { env: "PUNCAK BOGOR TEA PLANTATION VISIT", arch: "ROLLING GREEN HILLS OF TEA PLANT ROWS", props: "VINTAGE TOYOTA KIJANG IN BACKGROUND, MISTY MOUNTAINS", era_id: "Y2K_2000S" },
    { env: "ITC MANGGA DUA MALL CORRIDOR (JAKARTA)", arch: "CRAMPED SHOPS WITH BRIGHT NEON SIGNS AND LOW CEILINGS", props: "PILE OF CLOTHING STALLS, MANNEQUINS, PLASTIC BAGS", era_id: "Y2K_2000S" },
    { env: "MALIOBORO STREET YOGYAKARTA (2000s)", arch: "CROWDED PEDESTRIAN WALKWAY WITH BATIK STALLS AND HAWKERS", props: "LESEHAN FOOD MATS, STREET MUSICIANS WITH GUITAR", era_id: "Y2K_2000S" },
    { env: "AMPERA BRIDGE PALEMBANG AT NIGHT", arch: "RED ILLUMINATED BRIDGE OVER MUSI RIVER", props: "FLOATING RESTAURANT (WARUNG APUNG) BELOW, WATER REFLECTIONS", era_id: "Y2K_2000S" },
    { env: "KUTA BEACH BALI (2000s TOURIST ERA)", arch: "SANDY BEACH WITH OLD SURFBOARDS AND BEACH BARS", props: "TEMPORARY TATTOO STANDS, TOURISTS, BINTANG SINGLET", era_id: "Y2K_2000S" },
    { env: "CLASSIC UNDERGROUND CLUB IN JAKARTA (2000s)", arch: "DARK SWEATY DANCEFLOOR, LOW CEILING", props: "TRANCE MUSIC LASERS, PACKED CROWD, CHEAP DRINKS", era_id: "Y2K_2000S" },
    { env: "OLD MALL BATHROOM (TOILET MALL 2000S)", arch: "BASIC TILES AND FLUORESCENT OVERHEAD LIGHTING, LARGE MIRROR", props: "GRAFFITI ON STALL DOORS, OLD HAND DRYER", era_id: "Y2K_2000S" },
    { env: "MCDONALD'S DINE-IN (MEKDI 2000S)", arch: "RED AND YELLOW INTERIOR WITH PLASTIC BOOTHS AND TRAYS", props: "MCDONALDS PAPER BAGS, FRIES, HAPPY MEAL TOY, TRAY", era_id: "Y2K_2000S" },
    { env: "ANCOL DREAMLAND AMUSEMENT PARK JAKARTA", arch: "COLORFUL RIDE STRUCTURES, OPEN PARK GROUNDS", props: "ROLLERCOASTER IN BACKGROUND, COTTON CANDY", era_id: "Y2K_2000S" },
    { env: "LOCAL FUTSAL COURT (2000S)", arch: "INDOOR SMALL FOOTBALL COURT WITH ARTIFICIAL TURF AND CAGE NETTING", props: "FUTSAL BALL, BIBS, WORN TURF", era_id: "Y2K_2000S" },
    { env: "TERMINAL BLOK M JAKARTA (YEARS 2000)", arch: "CHAOTIC BUS TERMINAL WITH MULTIPLE BAYS, OLD SIGNAGE", props: "OLD JAKARTA METROMINI BUS, STREET VENDORS, KOPAJA", era_id: "Y2K_2000S" },
    { env: "KARAOKE ROOM (HAPPY PUPPY / NAV STYLE)", arch: "SMALL PRIVATE KARAOKE ROOM WITH COLORED LIGHTS AND DISCO BALL", props: "MICROPHONE, SONG BOOK BINDER, BEER BOTTLES, TV SCREEN", era_id: "Y2K_2000S" },
    { env: "TIMEZONE OR FUN WORLD ARCADE (MALL)", arch: "LOUD ARCADE HALL WITH BRIGHT MACHINES", props: "ARCADE MACHINES, TOKEN COINS, PRIZE COUNTER IN BACKGROUND", era_id: "Y2K_2000S" },

    // ===========================================================================
    // GRUNGE 1990S — Gritty, film-era Indonesia
    // ===========================================================================
    { env: "90s INDONESIAN BEDROOM", arch: "WOODEN WALL PANELING, MAGAZINE CUTOUT POSTERS OF INDOSIAR ARTISTS", props: "OLD BOX TV, CASSETTE TAPES, STANDING FAN, BANTAL GULING", era_id: "GRUNGE_1990S" },
    { env: "NARROW JAKARTA ALLEYWAY (GANG SEMPIT 90s)", arch: "OLD BRICK HOUSES CLOSE TOGETHER, LOW ELECTRICITY WIRES", props: "HANGING LAUNDRY ABOVE, WOODEN BENCH, STRAY CAT", era_id: "GRUNGE_1990S" },
    { env: "GRUNGY LOCAL ALLEY WITH OLD TORN POSTERS", arch: "PEELING PAINT, CEMENT WALLS WITH TORN ELECTION POSTERS", props: "TRASH BAG, OLD MOTORCYCLE PARKED, CHICKEN SCRATCHING AROUND", era_id: "GRUNGE_1990S" },
    { env: "TRADITIONAL WARKOP (WARUNG KOPI 90S)", arch: "WOODEN STALL WITH OLD BANNER, ZINC ROOF", props: "INSTANT NOODLE BOWLS, GLASS CUPS OF BLACK KOPI TUBRUK, RADIO", era_id: "GRUNGE_1990S" },
    { env: "BLOK M STREET HANGOUT (JAKARTA 90s)", arch: "BUSY STREET WITH 90s SHOPFRONTS AND FADED AWNINGS", props: "OLD JAKARTA METROMINI BUS IN THE BACKGROUND, STREET VENDORS", era_id: "GRUNGE_1990S" },
    { env: "OLD INDONESIAN TRAIN STATION (STASIUN JATINEGARA / SENEN)", arch: "DUTCH COLONIAL STATION ARCHITECTURE WITH HIGH CEILINGS", props: "VINTAGE TRAIN CARRIAGES, PLATFORM BENCHES, PLATFORM VENDORS", era_id: "GRUNGE_1990S" },
    { env: "MUDDY OUTDOOR PENSI (SCHOOL FESTIVAL 90s)", arch: "OPEN FIELD WITH A MAKESHIFT WOODEN STAGE AND BANNER", props: "CROWD OF TEENAGERS IN 90s CLOTHING, MUD ON SHOES", era_id: "GRUNGE_1990S" },
    { env: "LAKE TOBA OLD FERRY BOAT (NORTH SUMATRA)", arch: "RUSTY WOODEN PASSENGER BOAT ON CALM LAKE WATER", props: "FOGGY LAKE VIEW, OLD LUGGAGE BAGS, LIFE RINGS ON RAILING", era_id: "GRUNGE_1990S" },
    { env: "KAPUAS RIVER WOODEN DOCK PONTIANAK", arch: "RIVERSIDE WOODEN WARUNG KOPI, STILTED HOUSES", props: "TRADITIONAL COFFEE GLASSES, WOODEN BOATS, MUDDY WATER", era_id: "GRUNGE_1990S" },
    { env: "BOULEVARD MANADO BEFORE RECLAMATION", arch: "OLD SEASIDE ROAD WITH TREES", props: "STREET VENDORS, 90s MOTORCYCLES (HONDA ASTREA)", era_id: "GRUNGE_1990S" },
    { env: "OLD TAMAN MINI INDONESIA INDAH (TMII)", arch: "TRADITIONAL PAVILLION ARCHITECTURE FOR EACH PROVINCE", props: "1990S TOURISTS, MINIATURE LAKE IN BACKGROUND", era_id: "GRUNGE_1990S" },
    { env: "LOCAL BIOSKOP CINEMA (CINEMA 21 1990s)", arch: "OLD CINEMA EXTERIOR WITH HAND PAINTED MOVIE BILLBOARD", props: "QUEUE OF PEOPLE, OLD FILM POSTERS, TICKET BOOTH", era_id: "GRUNGE_1990S" }

];

// =============================================================================
// HOLIDAY LOCATION DATABASE
// =============================================================================

const holidayLocationDB = {
    "EID": [
        { env: "GRAND MOSQUE (MASJID AGUNG) COURTYARD AFTER PRAYERS", arch: "ISLAMIC ARCHITECTURE, MINARETS AND DOMES, HUGE COURTYARD", props: "PEOPLE GREETING AND HUGGING EACH OTHER, WHITE PRAYER CAPS, PRAYER MATS BEING FOLDED" },
        { env: "INDONESIAN FAMILY LIVING ROOM DURING LEBARAN", arch: "NEAT LIVING ROOM WITH CARPET AND FAMILY PHOTOS ON WALL", props: "JARS OF NASTAR AND KASTENGEL COOKIES, KETUPAT ON THE TABLE, RELATIVES SITTING" },
        { env: "RESIDENTIAL STREET DURING EID (JALAN DEPAN RUMAH)", arch: "QUIET NEIGHBORHOOD STREET WITH EID DECORATIONS", props: "FAMILIES IN BAJU KOKO AND GAMIS WALKING, CHILDREN COLLECTING ANGPAO" },
        { env: "AIRPORT DURING MUDIK LEBARAN (TERMINAL KEBERANGKATAN)", arch: "CROWDED DEPARTURE TERMINAL, LUGGAGE EVERYWHERE", props: "LONG QUEUES, FAMILIES WITH LARGE BAGS, DEPARTURES BOARD FULL" },
        { env: "BEDROOM WITH NEW EID OUTFIT LAID OUT", arch: "NEAT BEDROOM WITH LARGE FULL-LENGTH MIRROR", props: "NEW BAJU KOKO OR GAMIS HANGING, PRAYER MAT (SAJADAH), PARFUM" }
    ],
    "CHRISTMAS": [
        { env: "INDONESIAN CATHOLIC CHURCH INTERIOR (NATAL)", arch: "CHURCH ALTAR, WOODEN PEWS, STAINED GLASS WINDOWS", props: "CHRISTMAS DECORATIONS, CANDLES, NATIVITY SCENE" },
        { env: "LIVING ROOM WITH GLOWING CHRISTMAS TREE", arch: "WARM COZY INDONESIAN LIVING ROOM", props: "GLOWING CHRISTMAS TREE WITH ORNAMENTS, WRAPPED PRESENTS UNDERNEATH" },
        { env: "MALL WITH MASSIVE CHRISTMAS DECOR (JAKARTA MALL)", arch: "LUXURY MALL ATRIUM WITH HIGH CEILINGS", props: "GIANT CHRISTMAS TREE, FAKE SNOW MACHINES, MIRRORS, GIANT ORNAMENTS" },
        { env: "CHRISTMAS EVE FAMILY DINNER TABLE", arch: "FAMILY DINING ROOM WITH WARM LIGHTING", props: "ROAST CHICKEN OR TURKEY, CANDLES, CHRISTMAS CRACKERS, FAMILY SEATED" }
    ],
    "IMLEK": [
        { env: "CHINESE TEMPLE (VIHARA / KELENTENG) EXTERIOR", arch: "RED PILLARS, TRADITIONAL CHINESE SWEEPING ROOF, DRAGON STATUES", props: "RED LANTERNS HANGING, INCENSE SMOKE, WORSHIPPERS" },
        { env: "FAMILY DINING TABLE DURING LUNAR NEW YEAR", arch: "ASIAN DINING ROOM WITH RED AND GOLD DECORATIONS", props: "MANDARIN ORANGES IN BAMBOO BASKET, RED ENVELOPES (ANGPAO), SPECIAL DISHES" },
        { env: "GLODOK CHINATOWN STREET JAKARTA DURING IMLEK", arch: "NARROW STREET WITH OLD CHINESE SHOPHOUSES (RUKO)", props: "RED LANTERNS HANGING ACROSS THE STREET, DRAGON DANCE IN BACKGROUND" },
        { env: "LUXURY HOTEL LOBBY WITH IMLEK DECORATIONS", arch: "GRAND HOTEL LOBBY", props: "GIANT PUSSY WILLOW TREE WITH RED ENVELOPES, ORANGE TREES, GOLD DECORATIONS" }
    ],
    "GALUNGAN": [
        { env: "BALINESE PURA (TEMPLE) COURTYARD", arch: "TRADITIONAL BALINESE STONE SPLIT GATES (CANDI BENTAR), GREY STONE WALLS", props: "TRADITIONAL UMBRELLAS (TEDUNG), OFFERINGS (CANANG SARI) ON STEPS, INCENSE SMOKE" },
        { env: "BALI VILLAGE STREET DURING GALUNGAN", arch: "NARROW VILLAGE ROAD, TRADITIONAL BALINESE HOUSES", props: "TALL PENJOR BAMBOO POLES WITH COCONUT FROND DECORATIONS LINING THE STREET" },
        { env: "TRADITIONAL BALINESE HOUSE COMPOUND (NATAH)", arch: "BRICK COMPOUND WALLS, WOODEN PAVILIONS, FAMILY TEMPLE INSIDE", props: "OFFERINGS, INCENSE, FULL-LENGTH MIRROR, FAMILY IN CEREMONY CLOTHES" }
    ],
    "HUT_RI": [
        { env: "17 AGUSTUS UPACARA BENDERA (FLAG CEREMONY)", arch: "OPEN FIELD OR SCHOOL GROUND WITH FLAG POLE", props: "RED AND WHITE FLAG BEING RAISED, PARTICIPANTS IN WHITE UNIFORMS, MARCHING BAND" },
        { env: "17 AGUSTUS NEIGHBORHOOD COMPETITION FIELD (LOMBA)", arch: "RESIDENTIAL GANG OR SMALL FIELD", props: "MERAH PUTIH BANNERS, PANJAT PINANG POLE, CHEERFUL CROWD, FOLDING CHAIRS" },
        { env: "MONAS AREA JAKARTA ON INDEPENDENCE DAY", arch: "GRAND NATIONAL MONUMENT AREA, WIDE PLAZA", props: "CROWDS, MERAH PUTIH FLAGS EVERYWHERE, FIREWORKS SMOKE IN BACKGROUND" },
        { env: "FAMILY HOUSE WITH 17 AGUSTUS DECORATIONS", arch: "RESIDENTIAL HOUSE FACADE WITH GATE AND GARDEN", props: "MERAH PUTIH FLAGS AND BUNTING HANGING, PAPER LANTERNS, NEIGHBORHOOD VIBE" }
    ],
    "NYEPI": [
        { env: "BALINESE STREET BEFORE NYEPI (OGOH-OGOH PARADE)", arch: "VILLAGE STREET AT NIGHT, VERY CROWDED", props: "GIANT OGOH-OGOH MONSTERS BEING PARADED, FIRE TORCHES, GAMELAN PLAYERS" },
        { env: "BALI VILLA DURING NYEPI DAY (COMPLETELY DARK AND QUIET)", arch: "VILLA INTERIOR WITH TRADITIONAL DECOR", props: "CANDLELIGHT ONLY, ABSOLUTELY SILENT OUTSIDE, DARK SKY WITH NO LIGHT POLLUTION" }
    ]
};
